In [20]:
import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select
from webdriver_manager.chrome import ChromeDriverManager

def collecting_data():
    # Collecting data
    vehicle_id = []
    vehicle_title = []
    vehicle_make = []
    vehicle_model = []
    vehicle_body_type = []
    vehicle_year = []
    vehicle_mileage = []
    vehicle_transmission = []
    vehicle_variant = []
    vehicle_type = []
    vehicle_price = []
    vehicle_location = []
    vehicle_link = []

    container = driver.find_elements(By.XPATH, "/html/body/main/div[2]/div/div/div/div/section/article")
    for i in range(len(container)):
        vehicle_id.append(container[i].get_attribute("id"))
        vehicle_title.append(container[i].get_attribute("data-title"))
        vehicle_make.append(container[i].get_attribute("data-make"))
        vehicle_model.append(container[i].get_attribute("data-model"))
        vehicle_body_type.append(container[i].get_attribute("data-body-type"))
        vehicle_year.append(container[i].get_attribute("data-year"))
        vehicle_mileage.append(container[i].get_attribute("data-mileage"))
        vehicle_transmission.append(container[i].get_attribute("data-transmission"))
        vehicle_variant.append(container[i].get_attribute("data-variant"))
        vehicle_type.append(container[i].get_attribute("data-vehicle-type"))
        vehicle_price.append(container[i].text.split('\n')[5])
        vehicle_location.append(container[i].text.split('\n')[-4])
        vehicle_link.append(container[i].get_attribute("data-url"))
    
    
    temp = pd.DataFrame({
        'vehicle_id': vehicle_id,
        'vehicle_title': vehicle_title,
        'vehicle_make': vehicle_make,
        'vehicle_model': vehicle_model,
        'vehicle_body_type': vehicle_body_type,
        'vehicle_year': vehicle_year,
        'vehicle_mileage': vehicle_mileage,
        'vehicle_transmission': vehicle_transmission,
        'vehicle_variant': vehicle_variant,
        'vehicle_type': vehicle_type,
        'vehicle_price': vehicle_price,
        'vehicle_location': vehicle_location,
        'vehicle_location': vehicle_link    
    })
    
    return temp

web = "https://www.carmudi.co.id/mobil-bekas-dijual/indonesia"
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
driver.get(web)
driver.maximize_window()
time.sleep(5)

# Open the webiste
# click on last page
driver.find_element(By.XPATH, '//li[@class="last"]').click()
time.sleep(10)
# sorting by "update terakhir"
driver.find_element(By.XPATH, '//div[@class="flexbox__item  guide__input"]').click()
time.sleep(3)
driver.find_element(By.XPATH, '//div[@class="selectize-dropdown-content"]/div[2]').click()
time.sleep(3)

# dropdown_sorting = driver.find_element(By.XPATH, '//*[@id="classified-listings-result"]/div[4]/div/nav/div/div/div/select')
# dropdown_sorting_sel = Select(dropdown_sorting)
# dropdown_sorting_sel.select_by_visible_text("Update Terakhir")
df = collecting_data()
time.sleep(4)

for i in range(551):
    try:
        driver.find_element(By.XPATH, '//li[@class="prev"]').click()
        time.sleep(5)
        df2 = collecting_data()
        df = pd.concat([df, df2], axis=0).reset_index(drop=True)
        time.sleep(1)
    except:
        pass

driver.quit()

In [19]:
driver.quit()

In [22]:
df.to_csv("new_used_car2.csv")

In [7]:
df.vehicle_type.value_counts()

car    94
Name: vehicle_type, dtype: int64

In [21]:
df

,vehicle_id,vehicle_title,vehicle_make,vehicle_model,vehicle_body_type,vehicle_year,vehicle_mileage,vehicle_transmission,vehicle_variant,vehicle_type,vehicle_price,vehicle_location
0,listing_9121314,2016 Lexus RX200t 2.0 AL20 SUV TOTAL DP 225JT ...,Lexus,RX200t,SUV,2016,37500,Automatic,,car,Rp 915.000.000,https://www.carmudi.co.id/dijual/lexus-rx200t-...
1,listing_10198920,2014 Honda City 1.5 E Sedan AT Matic Hitam Paj...,Honda,City,Sedan,2014,72500,Automatic,E,car,Rp 172.000.000,https://www.carmudi.co.id/dijual/honda-city-e-...
2,listing_10143005,2010 BMW 523i 2.5 Executive Sedan,BMW,523i,Sedan,2010,197500,Automatic,Executive,car,Rp 215.000.000,https://www.carmudi.co.id/dijual/bmw-523i-exec...
3,listing_10034069,2017 Daihatsu Sigra 1.2 X Deluxe MPV PMK 2018 ...,Daihatsu,Sigra,MPV,2017,62500,Manual,X Deluxe,car,Rp 105.000.000,https://www.carmudi.co.id/dijual/daihatsu-sigr...
4,listing_10052411,"2010 Daihatsu Xenia 1.0 Li DELUXE+ MPV, FULL O...",Daihatsu,Xenia,MPV,2010,152500,Manual,Li DELUXE+,car,Rp 89.000.000,https://www.carmudi.co.id/dijual/daihatsu-xeni...
...,...,...,...,...,...,...,...,...,...,...,...,...
13596,listing_13073727,KM 71 RB. 98% SEPERTI BARU. Honda CRV 2.4 cc 2...,Honda,CR-V,SUV,2013,71000,Automatic,2.4 Prestige,car,Rp 195.000.000,https://www.carmudi.co.id/dijual/honda-cr-v-2-...
13597,listing_13073725,98% SEPERTI BARU. KM 71RB. Toyota Fortuner G L...,Toyota,Fortuner,SUV,2012,71000,Automatic,G Luxury,car,Rp 205.000.000,https://www.carmudi.co.id/dijual/toyota-fortun...
13598,listing_12008569,2015 Nissan Teana 2.5 XV Sedan,Nissan,Teana,Sedan,2015,75000,Automatic,XV,car,Rp 210.000.000,https://www.carmudi.co.id/dijual/nissan-teana-...
13599,listing_13234824,2015 Toyota Agya 1.0 TRD Sportivo Hatchback Au...,Toyota,Agya,Hatchback,2015,94824,Automatic,TRD Sportivo,car,Rp 110.000.000,https://www.carmudi.co.id/dijual/toyota-agya-t...
13600,listing_13149346,2020 Mercedes-Benz GLE450 3.0 4MATIC AMG Line ...,Mercedes-Benz,GLE450,Wagon,2020,17500,Automatic,4MATIC AMG Line,car,Rp 1.350.000.000,https://www.carmudi.co.id/dijual/mercedes-benz...